# SITE CONFIGURATION
url: 'https://lostisland.github.io'
baseurl: '/faraday'

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  title: Faraday
  # email: your-email@example.com
  description: >-
    Simple, but flexible HTTP client library, with support for multiple backends
  footer_text: Footer text for Faraday

  # Icons
  github: 'lostisland/faraday'

  # Post navigation
  post_navigation: false

# BUILD SETTINGS
markdown: kramdown
remote_theme: rohanchandra/type-theme
plugins:
  - jekyll-feed

# GitHub settings
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
